name: Update version.json
on:
  push:
    branches:
      - main  # Ana branch üzerinde değişiklik olduğunda tetiklenir
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Update version.json
        run: |
          mkdir -p public  # public klasörünü oluşturuyoruz
          echo '{
            "index.html": "v2",
            "home_en.html": "v9",
            "home_tr.html": "v7",
            "404.html": "v2",
            "CSS/unpkg.comswiper@8swiper-bundle.min.css": "v1",
            "FONTS/Inconsolata.woff2": "v1",
            "FONTS/Jaro.woff2": "v1",
            "FONTS/Monomakh.woff2": "v1",
            "FONTS/Montserrat.woff2": "v1",
            "FONTS/TacOne.woff2": "v1",
            "FONTS/Teko.woff2": "v1",
            "JAVASCRIPT/1.js": "v4",
            "JAVASCRIPT/tr/1.js": "v4",
            "JAVASCRIPT/darkmode-js.min.js": "v1",
            "JAVASCRIPT/gsap.min.js": "v1",
            "JAVASCRIPT/swiper-bundle.min.js": "v1",
            "img/profile_photo1.webp": "v1",
            "img/character1.webp": "v2",
            "img/character2.webp": "v1",
            "img/character3.webp": "v1",
            "img/ai.webp": "v1",
            "img/app.webp": "v1",
            "img/cyber.webp": "v1",
            "img/game.webp": "v1",
            "img/robotic.webp": "v1",
            "img/web.webp": "v1",
            "img/up.webp": "v1",
            "img/icon.ico": "v1",
            "sitemap.xml": "v1",
            "manifest.json": "v1",
            "robots.txt": "v1",
            ".htaccess.txt": "v1"
          }' > /public/version.json  # Versiyon bilgilerini public/ dizinine yazıyoruz
